# Generated by Django 6.0.7 on 2026-07-17 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("MONTHLY_RANGE", "Monthly range"),
                            ("MONTHLY_FIXED", "Monthly fixed"),
                            ("PERFORMANCE", "Performance"),
                        ],
                        max_length=30,
                    ),
                ),
                ("currency", models.CharField(default="JPY", max_length=3)),
                ("hourly_rate", models.PositiveBigIntegerField(blank=True, null=True)),
                ("monthly_rate", models.PositiveBigIntegerField(blank=True, null=True)),
                ("base_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "deduction_rate",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "overtime_rate",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "performance_amount",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("rounding_unit_minutes", models.PositiveSmallIntegerField(default=1)),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("FLOOR", "Floor"),
                            ("CEIL", "Ceil"),
                            ("ROUND", "Round"),
                        ],
                        default="FLOOR",
                        max_length=10,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_contracts",
                "indexes": [
                    models.Index(
                        fields=["organization", "project", "valid_from"],
                        name="contract_org_proj_from_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_from__lte", models.F("valid_until")),
                            _connector="OR",
                        ),
                        name="contracts_date_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tax_rate__gte", 0), ("tax_rate__lte", 100)
                        ),
                        name="contracts_tax_rate_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("withholding_tax_rate__gte", 0),
                            ("withholding_tax_rate__lte", 100),
                        ),
                        name="contracts_withhold_range",
                    ),
                ],
            },
        ),
    ]
