# Generated by Django 6.0.7 on 2026-07-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcontract",
            name="rounding_method",
            field=models.CharField(
                choices=[
                    ("ROUND_DOWN", "Round down"),
                    ("ROUND_UP", "Round up"),
                    ("ROUND_HALF_UP", "Round half up"),
                ],
                default="ROUND_DOWN",
                max_length=20,
            ),
        ),
    ]
