# Generated by Django 6.0.7 on 2026-07-21

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_business_profiles(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Profile = apps.get_model("organizations", "OrganizationBusinessProfile")
    Profile.objects.bulk_create(
        [
            Profile(organization_id=organization_id)
            for organization_id in Organization.objects.values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )


def remove_business_profiles(apps, schema_editor):
    apps.get_model(
        "organizations", "OrganizationBusinessProfile"
    ).objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_settings"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationBusinessProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("postal_code", models.CharField(blank=True, default="", max_length=8)),
                ("prefecture", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "invoice_registration_number",
                    models.CharField(blank=True, default="", max_length=14),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"db_table": "organization_business_profiles"},
        ),
        migrations.RunPython(create_business_profiles, remove_business_profiles),
    ]
