# Generated by Django 6.0.7 on 2026-07-17 03:28

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("IMAGE_PROCESSING", "Image processing"),
                            ("FILE_DELETE", "File delete"),
                            ("OUTBOX_DISPATCH", "Outbox dispatch"),
                            ("CLEANUP", "Cleanup"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="background_tasks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "background_tasks",
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "created_at"],
                        name="bg_tasks_org_status_created_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("progress__gte", 0), ("progress__lte", 100)
                        ),
                        name="background_tasks_progress_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CLIENT_ICON", "Client icon"),
                            ("PROJECT_ICON", "Project icon"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("CLOUDFLARE_R2", "Cloudflare R2"),
                        ],
                        default="LOCAL",
                        max_length=30,
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "original_object_key",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "processed_object_key",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "variants",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_files",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "stored_files",
                "indexes": [
                    models.Index(
                        fields=["organization", "category", "status"],
                        name="stored_files_org_cat_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("file_size_bytes__gte", 0),
                            ("file_size_bytes__isnull", True),
                            _connector="OR",
                        ),
                        name="stored_files_size_nonnegative",
                    )
                ],
            },
        ),
    ]
