# Generated by Django 6.0.7 on 2026-07-17 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backgroundtask",
            new_name="bgtask_org_status_created_idx",
            old_name="bg_tasks_org_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="storedfile",
            new_name="stored_org_cat_status_idx",
            old_name="stored_files_org_cat_status_idx",
        ),
    ]
