# Generated by Django 6.0.7 on 2026-07-17 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "icon_type",
                    models.CharField(
                        choices=[("DEFAULT", "Default"), ("UPLOADED", "Uploaded")],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                (
                    "icon_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("icon_updated_at", models.DateTimeField(blank=True, null=True)),
                ("default_icon_text", models.CharField(max_length=4)),
                ("default_icon_background_color", models.CharField(max_length=7)),
                ("default_icon_text_color", models.CharField(max_length=7)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clients",
            },
        ),
    ]
