# Generated by Django 6.0.7 on 2026-07-17 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("files", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="icon_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_icons",
                to="files.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["organization", "status", "updated_at"],
                name="clients_org_status_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["organization", "name"], name="clients_org_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "name"),
                name="clients_active_org_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("icon_file__isnull", True), ("icon_type", "DEFAULT")),
                    models.Q(("icon_file__isnull", False), ("icon_type", "UPLOADED")),
                    _connector="OR",
                ),
                name="clients_icon_type_file_consistent",
            ),
        ),
    ]
