# Generated by Django 6.0.7 on 2026-07-17 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_schedules",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_weekly_schedules",
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=150)),
                ("scheduled_start_at", models.DateTimeField()),
                ("scheduled_end_at", models.DateTimeField()),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("PLANNED", "Planned"), ("CANCELLED", "Cancelled")],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("is_manually_overridden", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_schedules",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_work_schedules",
                        to="schedules.weeklyschedule",
                    ),
                ),
            ],
            options={
                "db_table": "work_schedules",
            },
        ),
        migrations.AddIndex(
            model_name="weeklyschedule",
            index=models.Index(
                fields=["organization", "project", "status"],
                name="wkly_org_proj_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyschedule",
            index=models.Index(
                fields=["organization", "user", "day_of_week"],
                name="wkly_org_user_day_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 0), ("day_of_week__lte", 6)),
                name="weekly_schedules_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="weekly_schedules_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_from__lte", models.F("valid_until")),
                    _connector="OR",
                ),
                name="weekly_schedules_date_range",
            ),
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=[
                    "organization",
                    "user",
                    "scheduled_start_at",
                    "scheduled_end_at",
                ],
                name="work_org_user_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=["organization", "project", "scheduled_start_at"],
                name="work_org_proj_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workschedule",
            index=models.Index(
                fields=["weekly_schedule", "scheduled_start_at"],
                name="work_source_start_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_start_at__lt", models.F("scheduled_end_at"))
                ),
                name="work_schedules_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="workschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_generated", False), ("weekly_schedule__isnull", True)
                    ),
                    models.Q(
                        ("is_generated", True), ("weekly_schedule__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="work_schedules_source_valid",
            ),
        ),
    ]
