# Generated by Django 6.0.7 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="compact_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="family_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="given_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="time_format",
            field=models.CharField(
                choices=[("H24", "24-hour"), ("H12", "12-hour")],
                default="H24",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="week_starts_on",
            field=models.CharField(
                choices=[("MONDAY", "Monday"), ("SUNDAY", "Sunday")],
                default="MONDAY",
                max_length=10,
            ),
        ),
    ]
