# Generated by Django 6.0.7 on 2026-07-17 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        (
            "files",
            "0002_rename_bg_tasks_org_status_created_idx_bgtask_org_status_created_idx_and_more",
        ),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("label_color", models.CharField(max_length=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "workload_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "icon_type",
                    models.CharField(
                        choices=[("DEFAULT", "Default"), ("UPLOADED", "Uploaded")],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                (
                    "icon_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("icon_updated_at", models.DateTimeField(blank=True, null=True)),
                ("default_icon_text", models.CharField(max_length=4)),
                ("default_icon_background_color", models.CharField(max_length=7)),
                ("default_icon_text_color", models.CharField(max_length=7)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icon_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_icons",
                        to="files.storedfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MANAGER", "Manager"), ("MEMBER", "Member")],
                        max_length=20,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit_schedule", models.BooleanField(default=False)),
                ("can_edit_work_record", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_members",
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "status", "updated_at"],
                name="proj_org_status_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "client", "name"],
                name="projects_org_client_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("client", "name"),
                name="projects_active_client_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("end_date__isnull", True),
                    ("start_date__lte", models.F("end_date")),
                    _connector="OR",
                ),
                name="projects_date_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("workload_rate__isnull", True),
                    models.Q(("workload_rate__gte", 0), ("workload_rate__lte", 100)),
                    _connector="OR",
                ),
                name="projects_workload_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("icon_file__isnull", True), ("icon_type", "DEFAULT")),
                    models.Q(("icon_file__isnull", False), ("icon_type", "UPLOADED")),
                    _connector="OR",
                ),
                name="projects_icon_type_file_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["organization", "project"],
                name="projmem_org_project_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["organization", "user"], name="project_members_org_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("project", "user"),
                name="project_members_active_project_user_uniq",
            ),
        ),
    ]
