# Generated by Django 6.0.7 on 2026-07-17 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyProjectSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("settlement_month", models.DateField()),
                (
                    "calculation_basis",
                    models.CharField(
                        choices=[("ACTUAL", "Actual"), ("SCHEDULED", "Scheduled")],
                        max_length=20,
                    ),
                ),
                ("scheduled_minutes", models.PositiveIntegerField(default=0)),
                ("actual_minutes", models.PositiveIntegerField(default=0)),
                ("billable_minutes", models.PositiveIntegerField(default=0)),
                ("base_amount", models.PositiveBigIntegerField(default=0)),
                ("deduction_amount", models.PositiveBigIntegerField(default=0)),
                ("overtime_amount", models.PositiveBigIntegerField(default=0)),
                ("tax_amount", models.PositiveBigIntegerField(default=0)),
                ("withholding_amount", models.PositiveBigIntegerField(default=0)),
                ("total_amount", models.BigIntegerField(default=0)),
                ("calculation_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CALCULATED", "Calculated"),
                            ("FINALIZED", "Finalized"),
                        ],
                        default="CALCULATED",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="contracts.projectcontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finalized_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "monthly_project_settlements",
            },
        ),
        migrations.CreateModel(
            name="SettlementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("BASE", "Base"),
                            ("DEDUCTION", "Deduction"),
                            ("OVERTIME", "Overtime"),
                            ("TAX", "Tax"),
                            ("WITHHOLDING", "Withholding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("amount", models.PositiveBigIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="organizations.organization",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="settlements.monthlyprojectsettlement",
                    ),
                ),
            ],
            options={
                "db_table": "settlement_lines",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "idempotency_keys",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user", "endpoint", "key"),
                        name="idempotency_scope_key_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="monthlyprojectsettlement",
            index=models.Index(
                fields=["organization", "settlement_month", "status"],
                name="settlement_org_month_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyprojectsettlement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organization", "project", "settlement_month"),
                name="settlement_active_month_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlyprojectsettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("finalized_at__isnull", True),
                        ("finalized_by__isnull", True),
                        ("status", "CALCULATED"),
                    ),
                    models.Q(
                        ("finalized_at__isnull", False),
                        ("finalized_by__isnull", False),
                        ("status", "FINALIZED"),
                    ),
                    _connector="OR",
                ),
                name="settlement_finalize_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementline",
            constraint=models.UniqueConstraint(
                fields=("settlement", "line_type"), name="settlement_line_type_uniq"
            ),
        ),
    ]
