# Generated by Django 6.0.7 on 2026-07-17 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("actual_start_at", models.DateTimeField()),
                ("actual_end_at", models.DateTimeField()),
                ("actual_minutes", models.PositiveIntegerField()),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                ("billable_minutes", models.PositiveIntegerField()),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to="schedules.workschedule",
                    ),
                ),
            ],
            options={
                "db_table": "work_records",
            },
        ),
        migrations.CreateModel(
            name="WorkRecordBreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("break_minutes", models.PositiveIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_record_breaks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "work_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="work_records.workrecord",
                    ),
                ),
            ],
            options={
                "db_table": "work_breaks",
                "ordering": ["sort_order", "start_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["organization", "user", "actual_start_at"],
                name="work_org_user_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["organization", "project", "actual_start_at"],
                name="record_org_proj_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["organization", "status", "actual_start_at"],
                name="work_org_status_start_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("actual_start_at__lt", models.F("actual_end_at"))),
                name="work_records_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="workrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_billable", True), ("billable_minutes", 0), _connector="OR"
                ),
                name="work_records_nonbillable_zero",
            ),
        ),
        migrations.AddIndex(
            model_name="workrecordbreak",
            index=models.Index(
                fields=["organization", "work_record"], name="work_break_org_record_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workrecordbreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_at__lt", models.F("end_at"))),
                name="work_breaks_time_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="workrecordbreak",
            constraint=models.UniqueConstraint(
                fields=("work_record", "sort_order"),
                name="work_breaks_record_order_uniq",
            ),
        ),
    ]
